version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: mylolstyle-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: >
      sh -c "pip install -r requirements.txt && python app.py"

  frontend:
    build:
      context: ./frontend
    container_name: mylolstyle-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    command: >
      sh -c "npm install && npm start"
